### PR TITLE
404 Error Page. Issue #37

### PR DESCRIPTION
**Pull request by rahulparmani**
Created a custom 404 Error page with a nice UI using HTML and CSS and tested it on multiple screen sizes and it works fine. 
404_img

### CODE REVIEW

**Comment by Chintan2108** [comment]
Hi @rahulparmani!
Thank you for your PR. Good work on the 404 page design. 
* However, I think you still need to implement the logic to check for the incorrect routing, as to when this page should be displayed. 
* Also, I encourage you to go through the general UI/UX of the [CyanoKhoj Website](http://34.67.7.17/CyanoKhoj/) and update this page design accordingly. 

Let me know if you have any queries.

**Comment by rahulparmani** [comment]
Hi @Chintan2108 Thanks for the review. I will go through the CyanoKhoj Website and update the design accordingly or design a new one. Also I will try to implement a logic as to when this page should be displayed. Can I go with it?

**Comment by rahulparmani** [comment]
Hi @Chintan2108 I have updated the design of the 404 page according to the CyanoKhoj's Website. 

Also for the incorrect routing, a file named as .htaccess needs to be created and updated which redirects to the custom 404 page.

I have created and updated the .htaccess file and tested it for incorrect routing and it displays the custom 404 page correctly instead of the default one. 

Also the the page is responsive and works well on different screen sizes. The .htaccess file needs to be kept in the CyanoKhoj directory and the custom 404 file should be kept in the root directory of the website.

If it looks fine I can create a PR which will consist of the 404 file and the .htaccess file. Below are the screenshots which shows the results for incorrect routing. Thanks.

Screenshot (16)

Screenshot (17)

**Comment by Chintan2108** [comment]
@rahulparmani Good work.
I'm going to merge the PR provisionally and check the functionality on the hosted server.
I will then review this PR.

**Review by Chintan2108 — CHANGES_REQUESTED** [review]
Cannot find the new changes that you have mentioned in your latest comment.
Yet to commit them?

**Comment by rahulparmani** [comment]
Yes @Chintan2108 Wanted your review first. I will commit them now. Thanks.

**Pull request closed without merging**
